name: Functions pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ main ]
  #   paths:
  #     - "functions/**"
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #     - "functions/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: functions/package-lock.json
      - run: npm install
        working-directory: ./functions
      - run: npm run lint
        working-directory: ./functions
      - run: npm run build
        working-directory: ./functions

  deployment-functions:
    name: Deploy functions
    concurrency:
      group: deployment-functions
      cancel-in-progress: true
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Functions
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: functions/package-lock.json
      - name: npm install
        working-directory: ./functions
        run: npm install
      - name: Build Functions
        working-directory: ./functions
        run: npm run build
      - name: Install firebase tools
        run: npm install -g firebase-tools
      - name: Firebase deploy functions
        run: firebase deploy --only functions --token ${{ secrets.FIREBASE_CI_TOKEN }}
