name: Hosting pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ main ]
  #   paths:
  #     - "hosting/**"
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #     - "hosting/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deployment-hosting:
    name: Deploy Hosting
    concurrency:
      group: deployment-hosting
      cancel-in-progress: true
    runs-on: ubuntu-latest
    environment:
      name: Hosting
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: hosting/package-lock.json
      - name: build hosting
        working-directory: 'hosting/'
        run: |
          npm install
          npm run build
      - name: Firebase deploy hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
